disabled_rules:
- trailing_whitespace
- switch_case_alignment
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
type_name:
    min_length: 1 # only warning
    max_length: # warning and error
        warning: 40
        error: 50
    excluded: iPhone # excluded via string
    allowed_symbols: ["_"] # these are allowed in type names
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 26
force_cast: warning
nesting:
    type_level: 3
identifier_name:
    allowed_symbols: "_"
    min_length: 2
    max_length:
      warning: 90
      error: 200
    excluded:
      - id
vertical_whitespace:
    max_empty_lines: 2
generic_type_name:
    min_length: 1
    max_length:
      warning: 30
      error: 40
reporter: "xcode"
